image: node:latest

stages:
  - test
  - build

frontend-test:
  stage: test
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run test
  artifacts:
    paths:
      - frontend/dist

backend-test:
  stage: test
  before_script:
    - cd backend
    - npm install
  script:
    - npm run test
  artifacts:
    paths:
      - backend/mochawesome-report