backend-test:
  stage: test
  variables:
    WORKDIR: backend
    JWT_SECRET: $CI_COMMIT_SHA
  before_script:
    - cd $WORKDIR
    - npm install
  script:
    - npm run test:ci
  artifacts:
    reports:
      junit: $WORKDIR/junit.xml