
backend-test:
  stage: test
  variables:
    WORKDIR: backend
  before_script:
    - cd $WORKDIR
    - npm install
  script:
    - npm run test
  artifacts:
    reports:
        junit: $WORKDIR/junit.xml